setGeneric("Ontologies", function(object) standardGeneric("Ontologies"))
setGeneric("Ontology", function(object) standardGeneric("Ontology"))

setGeneric("olsPrefix", function(object, ...) standardGeneric("olsPrefix"))
setGeneric("olsDesc", function(object, ...) standardGeneric("olsDesc"))
setGeneric("olsTitle", function(object, ...) standardGeneric("olsTitle"))
setGeneric("olsLabel", function(object, ...) standardGeneric("olsLabel"))
setGeneric("olsRoot", function(object, ...) standardGeneric("olsRoot"))
setGeneric("terms", function(x, ...) standardGeneric("terms"))
setGeneric("term", function(object, id, ...) standardGeneric("term"))
setGeneric("termId", function(object, ...) standardGeneric("termId"))
