setGeneric("Ontologies", function(object) standardGeneric("Ontologies"))
setGeneric("Ontology", function(object) standardGeneric("Ontology"))

setGeneric("olsPrefix", function(object, ...) standardGeneric("olsPrefix"))
setGeneric("olsDesc", function(object, ...) standardGeneric("olsDesc"))
setGeneric("olsTitle", function(object, ...) standardGeneric("olsTitle"))
setGeneric("olsLabel", function(object, ...) standardGeneric("olsLabel"))
setGeneric("olsRoot", function(object, ...) standardGeneric("olsRoot"))
setGeneric("terms", function(x, ...) standardGeneric("terms"))
setGeneric("term", function(object, id, ...) standardGeneric("term"))
setGeneric("termId", function(object, ...) standardGeneric("termId"))
setGeneric("olsVersion", function(object, ...) standardGeneric("olsVersion"))
setGeneric("olsLoaded", function(object, ...) standardGeneric("olsLoaded"))
setGeneric("olsUpdated", function(object, ...) standardGeneric("olsUpdated"))
setGeneric("isObsolete", function(object, ...) standardGeneric("isObsolete"))
setGeneric("isRoot", function(object, ...) standardGeneric("isRoot"))
setGeneric("olsSynonym", function(object, ...) standardGeneric("olsSynonym"))
setGeneric("olsStatus", function(object, ...) standardGeneric("olsStatus"))
