setGeneric("olsPrefix", function(object, ...) standardGeneric("olsPrefix"))
setGeneric("olsDesc", function(object, ...) standardGeneric("olsDesc"))
setGeneric("olsTitle", function(object, ...) standardGeneric("olsTitle"))
setGeneric("olsTitle", function(object, ...) standardGeneric("olsTitle"))
setGeneric("olsRoot", function(object, ...) standardGeneric("olsRoot"))
setGeneric("terms", function(object, ...) standardGeneric("terms"))
setGeneric("term", function(object, id, ...) standardGeneric("term"))
setGeneric("termId", function(object, ...) standardGeneric("termId"))
setGeneric("ontologies", function(object) standardGeneric("ontologies"))
setGeneric("olsQuery", function(object,  ...) standardGeneric("olsQuery"))
